options:
  install_sources:
    description: charm-helpers standard listing of package install sources.
    type: string
    default: |
        - "deb http://ppa.launchpad.net/saltstack/salt/ubuntu trusty main"
        - "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main"
  install_keys:
    description: |
        charm-helpers standard listing of package install source signing keys,
        corresponding to install_sources.
    type: string
    default: |
        - 0E27C0A6
        - ACCC4CF8
  admin-username:
    description:
    type: string
    default: ""
  admin-password:
    description:
    type: string
    default: ""
  admin-email:
    description:
    type: string
    default: ""
